# Generated by Django 4.2.13 on 2026-08-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_alter_collectionnotice_collection_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, help_text='Set by the market agent when placing the order — e.g. handling instructions.'),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_delivery_method',
            field=models.CharField(blank=True, choices=[('SELF_COLLECTION', 'Agent Self-Collection'), ('TRANSPORTER_DELIVERY', 'Distributor-Arranged Transporter Delivery')], max_length=30, null=True),
        ),
    ]
