"""
Scheduled report generation — see config/celery.py beat_schedule for when these run.
Both tasks build a real PDF/Excel file and save it onto a Report row (status READY),
matching the "All reports are generated by Celery background jobs — users never wait"
design in apps/reports/models.py. Falls back to status FAILED with error_message set
if generation raises, rather than leaving the row stuck at GENERATING forever.
"""

import io
from datetime import timedelta

from celery import shared_task
from django.core.files.base import ContentFile
from django.db.models import Avg, Sum, Count, Q
from django.utils import timezone

from .models import Report


def _excel_bytes(title, headers, rows):
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment
    from openpyxl.utils import get_column_letter

    wb = Workbook()
    ws = wb.active
    ws.title = 'Report'
    ws.append([title])
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=max(len(headers), 1))
    ws['A1'].font = Font(bold=True, size=14, color='1A5C34')
    ws.append([])

    header_row_idx = 3
    ws.append(headers)
    header_fill = PatternFill(start_color='1A5C34', end_color='1A5C34', fill_type='solid')
    for cell in ws[header_row_idx]:
        cell.font = Font(bold=True, color='FFFFFF')
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal='center')

    for row in rows:
        ws.append(row)

    for col_idx in range(1, len(headers) + 1):
        col_letter = get_column_letter(col_idx)
        values = [str(c.value) for c in ws[col_letter] if c.value is not None]
        width = min(max((len(v) for v in values), default=10) + 2, 40)
        ws.column_dimensions[col_letter].width = width
    ws.freeze_panes = f'A{header_row_idx + 1}'

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf.getvalue()


def _save_report_file(report, content_bytes, ext):
    filename = f"{report.report_type.lower()}_{report.period_end}.{ext}"
    report.file_path.save(filename, ContentFile(content_bytes), save=False)
    report.file_size_kb = max(1, len(content_bytes) // 1024)
    report.status = Report.Status.READY
    report.completed_at = timezone.now()
    report.save()


def _district_loss_rows(period_start, period_end):
    from apps.traceability.models import Batch

    scored = Batch.objects.filter(
        dispatch_timestamp__date__gte=period_start,
        dispatch_timestamp__date__lte=period_end,
        total_loss_pct__isnull=False,
    )
    district_rows = list(
        scored.values('cooperative__district')
        .annotate(batches=Count('id'), volume=Sum('dispatch_weight_kg'), avg_loss=Avg('total_loss_pct'))
        .order_by('-avg_loss')
    )
    headers = ['District', 'Batches', 'Volume (kg)', 'Avg Loss (%)']
    rows = [
        [r['cooperative__district'] or 'Unknown', r['batches'],
         round(float(r['volume'] or 0), 1), round(float(r['avg_loss'] or 0), 2)]
        for r in district_rows
    ]
    return scored, headers, rows


@shared_task
def generate_national_kpi_report():
    """Weekly national KPI summary — Mondays 03:00, covering the 7 days ending yesterday."""
    from apps.reports.views import ExportReportView

    period_end = timezone.localdate() - timedelta(days=1)
    period_start = period_end - timedelta(days=6)

    report = Report.objects.create(
        report_type=Report.ReportType.NATIONAL_KPI_SUMMARY,
        title=f'National KPI Summary — {period_start} to {period_end}',
        format=Report.Format.PDF,
        status=Report.Status.GENERATING,
        period_start=period_start, period_end=period_end,
        generated_by_job=True,
    )
    try:
        scored, headers, rows = _district_loss_rows(period_start, period_end)

        from apps.traceability.models import Batch
        all_batches = Batch.objects.filter(
            dispatch_timestamp__date__gte=period_start, dispatch_timestamp__date__lte=period_end,
        )
        total = all_batches.count()
        report.data_completeness_pct = round(scored.count() / total * 100) if total else 100

        top_crops = list(
            scored.values('crop__name').annotate(avg_loss=Avg('total_loss_pct')).order_by('-avg_loss')[:5]
        )
        extra_sections = [(
            'Top 5 Highest-Loss Crops', ['Crop', 'Avg Loss (%)'],
            [[c['crop__name'] or 'Unknown', round(float(c['avg_loss'] or 0), 2)] for c in top_crops],
        )] if top_crops else None

        top10 = rows[:10]
        chart_spec = {
            'title': 'Avg Loss (%) by District (top 10)',
            'categories': [r[0] for r in top10],
            'series': [{'name': 'Avg Loss (%)', 'values': [r[3] for r in top10]}],
        } if top10 else None

        pdf_bytes = ExportReportView._build_pdf_bytes(
            report.title, headers, rows, 'Scheduled Job', 'System',
            extra_sections=extra_sections, chart_spec=chart_spec,
        )
        _save_report_file(report, pdf_bytes, 'pdf')
    except Exception as e:
        report.status = Report.Status.FAILED
        report.error_message = str(e)
        report.save()
        raise
    return report.id


@shared_task
def generate_monthly_reports():
    """
    Monthly district/crop/cold-chain reports — 1st of the month 04:00, covering the
    calendar month that just ended. Three separate Report rows, one per type.
    """
    from apps.reports.views import ExportReportView

    today = timezone.localdate()
    period_end = today.replace(day=1) - timedelta(days=1)
    period_start = period_end.replace(day=1)

    _generate_district_loss_report(period_start, period_end, ExportReportView)
    _generate_crop_loss_report(period_start, period_end)
    _generate_cold_chain_report(period_start, period_end, ExportReportView)


def _generate_district_loss_report(period_start, period_end, ExportReportView):
    report = Report.objects.create(
        report_type=Report.ReportType.DISTRICT_LOSS_REPORT,
        title=f'District Loss Report — {period_start} to {period_end}',
        format=Report.Format.PDF,
        status=Report.Status.GENERATING,
        period_start=period_start, period_end=period_end,
        generated_by_job=True,
    )
    try:
        scored, headers, rows = _district_loss_rows(period_start, period_end)
        chart_spec = {
            'title': 'Avg Loss (%) by District',
            'categories': [r[0] for r in rows[:10]],
            'series': [{'name': 'Avg Loss (%)', 'values': [r[3] for r in rows[:10]]}],
        } if rows else None
        pdf_bytes = ExportReportView._build_pdf_bytes(
            report.title, headers, rows, 'Scheduled Job', 'System', chart_spec=chart_spec,
        )
        _save_report_file(report, pdf_bytes, 'pdf')
    except Exception as e:
        report.status = Report.Status.FAILED
        report.error_message = str(e)
        report.save()
        raise


def _generate_crop_loss_report(period_start, period_end):
    from apps.traceability.models import Batch

    report = Report.objects.create(
        report_type=Report.ReportType.CROP_LOSS_REPORT,
        title=f'Crop Loss Report — {period_start} to {period_end}',
        format=Report.Format.EXCEL,
        status=Report.Status.GENERATING,
        period_start=period_start, period_end=period_end,
        generated_by_job=True,
    )
    try:
        scored = Batch.objects.filter(
            dispatch_timestamp__date__gte=period_start,
            dispatch_timestamp__date__lte=period_end,
            total_loss_pct__isnull=False,
        )
        crop_rows = list(
            scored.values('crop__name')
            .annotate(batches=Count('id'), volume=Sum('dispatch_weight_kg'), avg_loss=Avg('total_loss_pct'))
            .order_by('-avg_loss')
        )
        headers = ['Crop', 'Batches', 'Volume (kg)', 'Avg Loss (%)']
        rows = [
            [r['crop__name'] or 'Unknown', r['batches'],
             round(float(r['volume'] or 0), 1), round(float(r['avg_loss'] or 0), 2)]
            for r in crop_rows
        ]
        excel_bytes = _excel_bytes(report.title, headers, rows)
        _save_report_file(report, excel_bytes, 'xlsx')
    except Exception as e:
        report.status = Report.Status.FAILED
        report.error_message = str(e)
        report.save()
        raise


def _generate_cold_chain_report(period_start, period_end, ExportReportView):
    from apps.iot.models import IoTReading

    report = Report.objects.create(
        report_type=Report.ReportType.COLD_CHAIN_COMPLIANCE,
        title=f'Cold Chain Compliance Report — {period_start} to {period_end}',
        format=Report.Format.PDF,
        status=Report.Status.GENERATING,
        period_start=period_start, period_end=period_end,
        generated_by_job=True,
    )
    try:
        readings = IoTReading.objects.filter(
            timestamp__date__gte=period_start, timestamp__date__lte=period_end,
        )
        facility_rows = list(
            readings.values('facility__name', 'facility__cooperative__district')
            .annotate(
                total=Count('id'),
                breaches=Count('id', filter=Q(is_temperature_breach=True) | Q(is_humidity_breach=True)),
            )
            .order_by('facility__name')
        )
        headers = ['Facility', 'District', 'Readings', 'Breaches', 'Compliance (%)']
        rows = []
        for r in facility_rows:
            total = r['total']
            breaches = r['breaches']
            compliance = round((1 - breaches / total) * 100, 1) if total else 100.0
            rows.append([
                r['facility__name'], r['facility__cooperative__district'] or '—',
                total, breaches, compliance,
            ])
        pdf_bytes = ExportReportView._build_pdf_bytes(
            report.title, headers, rows, 'Scheduled Job', 'System',
        )
        _save_report_file(report, pdf_bytes, 'pdf')
    except Exception as e:
        report.status = Report.Status.FAILED
        report.error_message = str(e)
        report.save()
        raise
