# Generated by Django 4.2.13 on 2026-08-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_alter_collectionnotice_collection_deadline'),
        ('cooperatives', '0006_cooperativewastereport_crop'),
        ('market_agents', '0004_wastereport_crop_alter_collectionconfirmation_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=200)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A — Excellent'), ('B', 'Grade B — Good'), ('C', 'Grade C — Fair')], default='A', max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_price_records', to='cooperatives.crop')),
                ('market_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='market_agents.marketagent')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['crop', 'market_name', 'recorded_at'], name='market_agen_crop_id_709a9d_idx')],
            },
        ),
    ]
